services:
  - type: web
    name: markov-chain-chatbot
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: MAX_WORDS
        value: 150
      - key: INPUT_FILENAME
        value: aitw.txt,commedia.txt,brunori.txt
      - key: TEMPERATURE
        value: 0
